version: '3'

services:
  db:
    container_name: ${MONGO_DB_SERVER_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
    restart: always

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_SERVER_NAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    restart: always

  poke-app:
    depends_on:
      - db
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    environment:
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_SERVER_NAME}:27017
      DB_NAME: ${MONGO_DB_SERVER_NAME}
    ports:
      - 3000:3000
    restart: always

volumes:
  poke-vol:
    external: false
